[tool-chain]
solana-version = "2.1.0"
anchor_version = "0.31.1"

[features]
seeds = false

[programs.localnet]
amm_v3 = "HpNfyc2Saw7RKkQd8nEL4khUcuPhQ7WwY1B2qjx8jxFq"

[registry]
url = "https://github.com/raydium-io/raydium-amm-v3"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"
